# Generated by Django 5.1 on 2024-09-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="ratings",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="uploads",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="views",
            field=models.BigIntegerField(default=0),
        ),
    ]
