# Generated by Django 5.1 on 2024-09-28 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user',
            new_name='uploadedBy',
        ),
    ]
