# Generated by Django 5.1 on 2024-09-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_chatlist_alter_user_bookmarklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='displayName',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
